[Tedious] Update to latest version from v9.2.1
Thomas-Smyth/SquadJS pull request #265
Opened 2023-01-12 11:34 UTC by DrKittens

Latest version resolves a critical bug around xml dom.

Ref: https://github.com/advisories/GHSA-crh6-fp67-6883

Currently still testing impacts of this major version change but it hasnt broken MySQL connections for the app or SSJS so far. 

This is probably low-priority for the project as i dont think we do anything with untrusted XML.

2023-01-13 21:24 UTC, werewolfboy13 requested changes
Needs more testing before PR can be pushed as this is a major version bump.

2023-01-24 00:52 UTC, ect0s commented
I think our dependence on Tedious is due to Sequelize, and its an optional dependency there if I'm reading yarn info correctly. 

@werewolfboy13 I know you may hesitate, but this should a low impact.

2023-01-24 02:10 UTC, werewolfboy13 commented
> I think our dependence on Tedious is due to Sequelize, and its an optional dependency there if I'm reading yarn info correctly.
> 
> @werewolfboy13 I know you may hesitate, but this should a low impact.

I just want nothing to break, if it's optional should be fine. I'll push this on my internal tools and see what happens. This will occur in a couple days or so.

2023-01-24 02:12 UTC, werewolfboy13 approved these changes

2023-01-24 11:35 UTC, ect0s approved these changes

2023-01-24 11:35 UTC, merged