Update README.md
Thomas-Smyth/SquadJS pull request #304
Opened 2023-09-09 23:11 UTC by Buff-oG

Explained and informed how to tests DiscordServerStatus plugin can be tested and works.

2023-09-09 23:32 UTC, werewolfboy13 requested changes
[REJECTED] Cron jobs will overwrite this, needs to be added to https://github.com/Team-Silver-Sphere/SquadJS/blob/31aad28f7e369d7e46ce40f607252c16c9d4e7d8/squad-server/plugins/discord-server-status.js#L10 for it to work.

2023-09-10 00:18 UTC, Buff-oG commented
Is it okay after I edited the readme template, discord-server-status JS file stating with a Description of how to use the plugin and package json new version ID.

If not, please do not hesitate to guide me since it's the first time doing a PR on this project.

2023-09-10 00:21 UTC, werewolfboy13 requested changes, later dismissed

2023-09-10 00:21 UTC, werewolfboy13 commented on package.json
> +  "version": "3.7.1",
Please do not bump the versioning, that is done internally.

2023-09-10 00:21 UTC, werewolfboy13 commented on squad-server/plugins/discord-server-status.js
> +        description: 'Command name to get message. Discord bot requires "Message Content Intent" option to be checked via Discord Developer Porta. Otherwise your bot cannot read the chat/channel',
Typo

2023-09-10 00:29 UTC, Buff-oG commented on squad-server/plugins/discord-server-status.js
> +        description: 'Command name to get message. Discord bot requires "Message Content Intent" option to be checked via Discord Developer Porta. Otherwise your bot cannot read the chat/channel',
Woups...

2023-09-10 00:29 UTC, Buff-oG commented
Newer PR. Typo fixed.

2023-09-15 22:00 UTC, werewolfboy13 commented
Unable to push into this PR, will need access @Buff-oG

2023-09-15 22:48 UTC, closed without merging