Feat: Add @here & Server Name
Thomas-Smyth/SquadJS pull request #344
Opened 2024-01-24 20:15 UTC by IgnisAlienus

Adds the ability to turn on @here for Admin Requests in Discord. This allows for pinging of all ONLINE Squad Admins if the Admin Request is going to a Squad Admin only Channel.

Added the ServerName option so you can tell what server the request is coming from for communities with multi servers without having to create multi channels for each server's admin request notifs.

2024-01-25 14:38 UTC, IgnisAlienus commented
Updated to use a this.server.serverName instead of using a plugin option of this.options.serverName.

2024-01-25 15:27 UTC, fantinodavide commented
The readme file hasn't been updated when removing the server name option, also, updating it shouldn't be a manual process as there is a command and a pre-commit hook to automatically update the config file, readme, and lint/format the files affected by the changes.

2024-01-25 15:49 UTC, IgnisAlienus commented
> The readme file hasn't been updated when removing the server name option, also, updating it shouldn't be a manual process as there is a command and a pre-commit hook to automatically update the config file, readme, and lint/format the files affected by the changes.

Updated ReadME. 

Yeah, things are wonky in my fork/branch so it was easier for me to just modify the files directly in this PR.

2024-01-25 20:00 UTC, werewolfboy13 requested changes
Please do not manually edit the readme, please use `yarn lint`.

Please push a commit with that edit done if it hasn't already been ran.

2024-01-25 20:09 UTC, werewolfboy13 commented
@IgnisAlienus I see you removed the server name, was that intended?

2024-01-25 20:12 UTC, IgnisAlienus commented
> @IgnisAlienus I see you removed the server name, was that intended?

Yes. this.server.serverName returns the Server Name that I is fetched somewhere else in SquadJS

2024-02-05 02:20 UTC, werewolfboy13 approved these changes

2024-02-05 02:21 UTC, merged